version: "3"

services:
    navanjani-personal:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./src:/usr/share/nginx/html
        networks:
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.backend=nginx"
            - "traefik.port=80"
            - "traefik.frontend.rule=Host:navanjani.com"
        deploy:
          mode: replicated
          replicas: 1

networks:
  traefik:
    external: true